# Generated by Django 4.0.1 on 2022-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('realise_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
